name: Auto-Merge to Private Repo

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request in repo-private
        run: |
          # Use GitHub CLI or API to create a pull request in repo-private
          # Example:
          gh pr create --base main --head main --title "Auto-Merge from repo-public" --body "Changes from repo-public merged."
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # GitHub token for authentication
