name: Create PR to repo-private

on:
  push:
    branches:
      - main  # Adjust the branch name as per your requirement

jobs:
  create_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create PR in repo-private
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_PRIVATE_TOKEN }}
        branch: main  # Branch where changes are pushed
        title: 'Merge from repo-public'
        body: 'This PR is automatically created from repo-public.'
        base: master  # Base branch in repo-private where PR will be created (change it as needed)
        branch-suffix: '-public-merge'  # Suffix for the branch name in repo-private
