name: Push File

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create pull request
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_PRIVATE_TOKEN }}
        with:
          source_folder: '.' # Adjust the source folder if needed
          destination_repo: 'Anandaraj-SF4202/demo1'
          destination_folder: '.' # Adjust the destination folder if needed
          destination_base_branch: 'main'
          destination_head_branch: 'sync-branch' # New branch to create in the destination repo
          user_email: 'anandaraj.sf4202@gmail.com' # Your email address
          user_name: 'Anandaraj-SF4202' # Your name
